spring:
  freemarker:
    cache: true
#  thymeleaf:
#    cache: false
  datasource:
    url: jdbc:mysql://localhost/auth_database?useSSL=false&characterEncoding=utf8
    username: root
    password: admin
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /static/**